/* The following code was generated by JFlex 1.4.3 on 06/09/16 18:36 */

package Example;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.Location;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 06/09/16 18:36 from the specification file
 * <tt>/Users/gaston/UNIVERSIDAD/CUARTO/COMPILADORES/PROYECTO/compiler_project/jflex/Scanner.jflex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\56\1\31\1\0\2\56\22\0\1\56\1\35\3\0\1\45"+
    "\1\33\1\0\1\46\1\47\1\32\1\37\1\43\1\40\1\26\1\30"+
    "\1\25\11\24\1\0\1\44\1\42\1\36\1\41\2\0\32\55\1\52"+
    "\1\0\1\53\1\0\1\55\1\0\1\4\1\1\1\6\1\23\1\3"+
    "\1\17\1\27\1\21\1\14\1\54\1\5\1\7\1\54\1\12\1\11"+
    "\2\54\1\2\1\10\1\13\1\15\1\22\1\20\1\16\2\54\1\50"+
    "\1\34\1\51\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\12\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\2\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\11\2\1\27\5\2\2\0\1\30\1\0\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\13\2"+
    "\1\41\2\2\1\42\1\0\1\2\1\43\1\2\1\44"+
    "\3\2\1\45\4\2\1\46\1\47\1\50\2\2\1\51"+
    "\2\2\1\52\1\53\1\54\1\55\1\56\3\2\1\57"+
    "\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[108];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\57\0\u0292"+
    "\0\57\0\57\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\57\0\57\0\57\0\57\0\57\0\57"+
    "\0\57\0\57\0\57\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\353\0\u05e0\0\u060f\0\u063e"+
    "\0\u066d\0\u069c\0\u06cb\0\u0263\0\u06fa\0\u0729\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\u0758\0\u0787"+
    "\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff"+
    "\0\u092e\0\353\0\u095d\0\u098c\0\u06cb\0\u09bb\0\u09ea\0\353"+
    "\0\u0a19\0\353\0\u0a48\0\u0a77\0\u0aa6\0\353\0\u0ad5\0\u0b04"+
    "\0\u0b33\0\u0b62\0\353\0\57\0\353\0\u0b91\0\u0bc0\0\353"+
    "\0\u0bef\0\u0c1e\0\353\0\353\0\353\0\353\0\353\0\u0c4d"+
    "\0\u0c7c\0\u0cab\0\353\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[108];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\7\4\6\1\10"+
    "\1\11\2\6\1\12\1\13\1\6\1\14\1\6\1\15"+
    "\1\16\1\17\1\6\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\6"+
    "\1\2\1\21\60\0\1\6\1\44\6\6\1\45\14\6"+
    "\1\0\1\6\24\0\2\6\2\0\2\6\1\46\22\6"+
    "\1\0\1\6\24\0\2\6\2\0\6\6\1\47\6\6"+
    "\1\50\7\6\1\0\1\6\24\0\2\6\2\0\25\6"+
    "\1\0\1\6\24\0\2\6\2\0\6\6\1\51\1\6"+
    "\1\52\14\6\1\0\1\6\24\0\2\6\2\0\1\6"+
    "\1\53\23\6\1\0\1\6\24\0\2\6\2\0\11\6"+
    "\1\54\4\6\1\55\6\6\1\0\1\6\24\0\2\6"+
    "\2\0\3\6\1\56\2\6\1\57\1\6\1\60\14\6"+
    "\1\0\1\6\24\0\2\6\2\0\20\6\1\61\4\6"+
    "\1\0\1\6\24\0\2\6\2\0\10\6\1\62\14\6"+
    "\1\0\1\6\24\0\2\6\25\0\2\15\1\63\54\0"+
    "\2\64\1\63\60\0\1\65\1\0\1\66\57\0\1\67"+
    "\57\0\1\70\60\0\1\71\56\0\1\72\56\0\1\73"+
    "\56\0\1\74\56\0\1\75\56\0\1\76\21\0\2\6"+
    "\1\77\22\6\1\0\1\6\24\0\2\6\2\0\10\6"+
    "\1\100\14\6\1\0\1\6\24\0\2\6\2\0\12\6"+
    "\1\101\12\6\1\0\1\6\24\0\2\6\2\0\7\6"+
    "\1\102\15\6\1\0\1\6\24\0\2\6\2\0\12\6"+
    "\1\103\12\6\1\0\1\6\24\0\2\6\2\0\3\6"+
    "\1\104\21\6\1\0\1\6\24\0\2\6\2\0\11\6"+
    "\1\105\13\6\1\0\1\6\24\0\2\6\2\0\14\6"+
    "\1\106\10\6\1\0\1\6\24\0\2\6\2\0\12\6"+
    "\1\107\12\6\1\0\1\6\24\0\2\6\2\0\6\6"+
    "\1\110\16\6\1\0\1\6\24\0\2\6\2\0\10\6"+
    "\1\111\14\6\1\0\1\6\24\0\2\6\2\0\1\6"+
    "\1\112\23\6\1\0\1\6\24\0\2\6\2\0\13\6"+
    "\1\113\11\6\1\0\1\6\24\0\2\6\2\0\13\6"+
    "\1\114\11\6\1\0\1\6\24\0\2\6\25\0\2\115"+
    "\31\0\31\65\1\0\25\65\32\66\1\116\24\66\1\0"+
    "\3\6\1\117\21\6\1\0\1\6\24\0\2\6\2\0"+
    "\6\6\1\120\16\6\1\0\1\6\24\0\2\6\2\0"+
    "\14\6\1\121\10\6\1\0\1\6\24\0\2\6\2\0"+
    "\2\6\1\122\22\6\1\0\1\6\24\0\2\6\2\0"+
    "\2\6\1\123\22\6\1\0\1\6\24\0\2\6\2\0"+
    "\7\6\1\124\15\6\1\0\1\6\24\0\2\6\2\0"+
    "\12\6\1\125\12\6\1\0\1\6\24\0\2\6\2\0"+
    "\2\6\1\126\22\6\1\0\1\6\24\0\2\6\2\0"+
    "\2\6\1\127\22\6\1\0\1\6\24\0\2\6\2\0"+
    "\7\6\1\130\15\6\1\0\1\6\24\0\2\6\2\0"+
    "\3\6\1\131\21\6\1\0\1\6\24\0\2\6\2\0"+
    "\6\6\1\132\16\6\1\0\1\6\24\0\2\6\2\0"+
    "\22\6\1\133\2\6\1\0\1\6\24\0\2\6\1\0"+
    "\30\66\1\134\1\66\1\116\24\66\1\0\4\6\1\135"+
    "\20\6\1\0\1\6\24\0\2\6\2\0\1\6\1\136"+
    "\23\6\1\0\1\6\24\0\2\6\2\0\1\6\1\137"+
    "\23\6\1\0\1\6\24\0\2\6\2\0\7\6\1\140"+
    "\15\6\1\0\1\6\24\0\2\6\2\0\13\6\1\141"+
    "\11\6\1\0\1\6\24\0\2\6\2\0\25\6\1\0"+
    "\1\142\24\0\2\6\2\0\2\6\1\143\22\6\1\0"+
    "\1\6\24\0\2\6\2\0\12\6\1\144\12\6\1\0"+
    "\1\6\24\0\2\6\2\0\2\6\1\145\22\6\1\0"+
    "\1\6\24\0\2\6\2\0\11\6\1\146\13\6\1\0"+
    "\1\6\24\0\2\6\2\0\11\6\1\147\13\6\1\0"+
    "\1\6\24\0\2\6\2\0\11\6\1\150\13\6\1\0"+
    "\1\6\24\0\2\6\2\0\2\6\1\151\22\6\1\0"+
    "\1\6\24\0\2\6\2\0\14\6\1\152\10\6\1\0"+
    "\1\6\24\0\2\6\2\0\1\6\1\153\23\6\1\0"+
    "\1\6\24\0\2\6\2\0\2\6\1\154\22\6\1\0"+
    "\1\6\24\0\2\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3290];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\1\11\1\1\2\11\10\1\11\11"+
    "\17\1\2\0\1\1\1\0\10\11\17\1\1\0\15\1"+
    "\1\11\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[108];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public Scanner(java.io.InputStream r, ComplexSymbolFactory sf){
		this(r);
		this.sf=sf;
	}
	public Symbol symbol(String plaintext,int code){
    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar));
	}
	public Symbol symbol(String plaintext,int code, Integer number){
    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar),number);
	}
	public Symbol symbol(String plaintext,int code, Float number){
    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar),number);
	}
	public Symbol symbol(String plaintext,int code, Boolean bool){
    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar),bool);
	}
	private ComplexSymbolFactory sf;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { return symbol("Left Bracket",sym.LPAREN);
          }
        case 49: break;
        case 30: 
          { return symbol("Assign and Substract",sym.SUBASSIGNMENT);
          }
        case 50: break;
        case 2: 
          { return symbol("Id", sym.ID);
          }
        case 51: break;
        case 29: 
          { return symbol("Assign and Add",sym.ADDASSIGNMENT);
          }
        case 52: break;
        case 12: 
          { return symbol("Greater",sym.GREATER);
          }
        case 53: break;
        case 44: 
          { return symbol("While", sym.WHILE);
          }
        case 54: break;
        case 39: 
          { System.out.println("COMMENT IN SOMES LINE");
          }
        case 55: break;
        case 6: 
          { /* ignore white space. */
          }
        case 56: break;
        case 24: 
          { System.out.println("");
          }
        case 57: break;
        case 32: 
          { return symbol("Less or Equal",sym.LESSOREQ);
          }
        case 58: break;
        case 14: 
          { return symbol("Comma",sym.COMMA);
          }
        case 59: break;
        case 40: 
          { return symbol("Break", sym.BREAK);
          }
        case 60: break;
        case 9: 
          { return symbol("Assign",sym.EQUAL);
          }
        case 61: break;
        case 22: 
          { return symbol("Right Bracket",sym.RBRACKET);
          }
        case 62: break;
        case 15: 
          { return symbol("Semicolon",sym.SEMI);
          }
        case 63: break;
        case 28: 
          { return symbol("Equal To",sym.EQUALTO);
          }
        case 64: break;
        case 5: 
          { return symbol("Divided",sym.DIVIDED);
          }
        case 65: break;
        case 19: 
          { return symbol("Left Bracket",sym.LKEY);
          }
        case 66: break;
        case 21: 
          { return symbol("Left Bracket",sym.LBRACKET);
          }
        case 67: break;
        case 10: 
          { return symbol("Plus",sym.PLUS);
          }
        case 68: break;
        case 16: 
          { return symbol("Percentage",sym.PERCENTAGE);
          }
        case 69: break;
        case 43: 
          { return symbol("Float", sym.FLOAT);
          }
        case 70: break;
        case 36: 
          { return symbol("Else", sym.ELSE);
          }
        case 71: break;
        case 8: 
          { return symbol("Not", sym.NOT);
          }
        case 72: break;
        case 34: 
          { return symbol("Float Number",sym.NUMBER_F, new Float(yytext()));
          }
        case 73: break;
        case 26: 
          { return symbol("Or", sym.OR);
          }
        case 74: break;
        case 25: 
          { return symbol("And", sym.AND);
          }
        case 75: break;
        case 33: 
          { return symbol("For", sym.FOR);
          }
        case 76: break;
        case 11: 
          { return symbol("Minus",sym.MINUS);
          }
        case 77: break;
        case 48: 
          { return symbol("Continue", sym.CONTINUE);
          }
        case 78: break;
        case 20: 
          { return symbol("Right Bracket",sym.RKEY);
          }
        case 79: break;
        case 45: 
          { return symbol("Return", sym.RETURN);
          }
        case 80: break;
        case 41: 
          { return symbol("Class", sym.CLASS);
          }
        case 81: break;
        case 18: 
          { return symbol("Right Bracket",sym.RPAREN);
          }
        case 82: break;
        case 3: 
          { return symbol("Integral Number",sym.NUMBER_I, new Integer(yytext()));
          }
        case 83: break;
        case 1: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 84: break;
        case 7: 
          { return symbol("Times",sym.TIMES);
          }
        case 85: break;
        case 27: 
          { return symbol("Not Equal To",sym.NOTEQUALTO);
          }
        case 86: break;
        case 42: 
          { return symbol("False", sym.BOOLEAN_VALUE, false);
          }
        case 87: break;
        case 13: 
          { return symbol("Less",sym.LESS);
          }
        case 88: break;
        case 37: 
          { return symbol("True", sym.BOOLEAN_VALUE, true);
          }
        case 89: break;
        case 31: 
          { return symbol("Greater or Equal",sym.GREATEROREQ);
          }
        case 90: break;
        case 35: 
          { return symbol("Bool", sym.BOOL);
          }
        case 91: break;
        case 23: 
          { return symbol("If", sym.IF);
          }
        case 92: break;
        case 46: 
          { return symbol("Extern", sym.EXTERN);
          }
        case 93: break;
        case 4: 
          { return symbol("Point",sym.POINT);
          }
        case 94: break;
        case 38: 
          { return symbol("Void", sym.VOID);
          }
        case 95: break;
        case 47: 
          { return symbol("Integer", sym.INTEGER);
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return sf.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
