/* The following code was generated by JFlex 1.4.3 on 30/08/16 12:27 */

package Example;

import java_cup.runtime.*;
import java_cup.runtime.ComplexSymbolFactory.Location;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30/08/16 12:27 from the specification file
 * <tt>/Users/gaston/UNIVERSIDAD/CUARTO/COMPILADORES/PROYECTO/compiler_project/jflex/Scanner.jflex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\41\1\30\1\0\2\41\22\0\1\27\7\0\1\36\1\37"+
    "\1\32\1\34\1\0\1\35\1\0\1\31\12\40\1\0\1\33\5\0"+
    "\32\26\6\0\1\6\1\1\1\10\1\21\1\5\1\16\1\17\1\23"+
    "\1\14\1\25\1\7\1\3\1\25\1\12\1\2\2\25\1\4\1\11"+
    "\1\13\1\15\1\20\1\22\1\24\2\25\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\15\1\1\3\1\4\1\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\1\1\14\12\1"+
    "\1\15\5\1\1\16\1\17\1\0\5\1\1\20\2\1"+
    "\1\21\3\1\1\22\4\1\1\0\1\23\2\1\1\24"+
    "\3\1\1\25\4\1\1\26\1\1\1\27\1\30\3\1"+
    "\1\31\1\0\1\1\1\32\1\1\1\33\1\34\1\35"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\36\1\0"+
    "\1\37\1\40\2\0\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\u01dc\0\u01fe"+
    "\0\42\0\u0220\0\42\0\42\0\42\0\42\0\42\0\42"+
    "\0\u0242\0\u0264\0\u0286\0\210\0\u02a8\0\u02ca\0\u02ec\0\u030e"+
    "\0\u0330\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da\0\210\0\u03fc"+
    "\0\u041e\0\u0440\0\u0462\0\u0484\0\u04a6\0\u04c8\0\u04ea\0\u050c"+
    "\0\u052e\0\u0550\0\u0572\0\u0594\0\210\0\u05b6\0\u05d8\0\210"+
    "\0\u05fa\0\u061c\0\u063e\0\210\0\u0660\0\u0682\0\u06a4\0\u06c6"+
    "\0\u06e8\0\210\0\u070a\0\u072c\0\210\0\u074e\0\u0770\0\u0792"+
    "\0\210\0\u07b4\0\u07d6\0\u07f8\0\u081a\0\210\0\u083c\0\42"+
    "\0\210\0\u085e\0\u0880\0\u08a2\0\210\0\u08c4\0\u08e6\0\210"+
    "\0\u0908\0\210\0\210\0\210\0\u092a\0\u094c\0\u096e\0\u0990"+
    "\0\u09b2\0\u09d4\0\210\0\u09f6\0\210\0\42\0\u0a18\0\u0a3a"+
    "\0\42";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\5"+
    "\1\11\1\5\1\12\1\13\1\14\1\5\1\15\1\5"+
    "\1\16\1\5\1\17\3\5\1\20\2\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\21\43\0"+
    "\1\5\1\32\1\5\1\33\21\5\15\0\3\5\1\34"+
    "\21\5\15\0\25\5\15\0\4\5\1\35\20\5\15\0"+
    "\2\5\1\36\20\5\1\37\1\5\15\0\11\5\1\40"+
    "\13\5\15\0\1\5\1\41\1\42\22\5\15\0\1\5"+
    "\1\43\12\5\1\44\10\5\15\0\3\5\1\45\21\5"+
    "\15\0\11\5\1\46\3\5\1\47\7\5\15\0\1\5"+
    "\1\50\1\51\2\5\1\52\17\5\15\0\1\5\1\53"+
    "\23\5\15\0\22\5\1\54\2\5\15\0\25\55\1\20"+
    "\44\0\1\56\1\57\47\0\1\31\2\0\1\5\1\60"+
    "\23\5\15\0\4\5\1\61\20\5\15\0\12\5\1\62"+
    "\12\5\15\0\10\5\1\63\14\5\15\0\12\5\1\64"+
    "\12\5\15\0\20\5\1\65\4\5\15\0\11\5\1\66"+
    "\13\5\15\0\5\5\1\67\17\5\15\0\12\5\1\70"+
    "\12\5\15\0\2\5\1\71\22\5\15\0\14\5\1\72"+
    "\10\5\15\0\12\5\1\73\12\5\15\0\3\5\1\74"+
    "\21\5\15\0\1\5\1\75\23\5\15\0\2\5\1\76"+
    "\22\5\15\0\13\5\1\77\11\5\15\0\13\5\1\100"+
    "\11\5\15\0\25\55\14\0\30\56\1\0\11\56\32\57"+
    "\1\101\7\57\1\0\2\5\1\102\22\5\15\0\5\5"+
    "\1\103\17\5\15\0\14\5\1\104\10\5\15\0\4\5"+
    "\1\105\20\5\15\0\4\5\1\106\20\5\15\0\12\5"+
    "\1\107\12\5\15\0\10\5\1\110\14\5\15\0\2\5"+
    "\1\111\22\5\15\0\4\5\1\112\20\5\15\0\4\5"+
    "\1\113\20\5\15\0\5\5\1\114\17\5\15\0\10\5"+
    "\1\115\14\5\15\0\20\5\1\116\4\5\15\0\2\5"+
    "\1\117\22\5\14\0\31\57\1\120\1\101\7\57\1\0"+
    "\6\5\1\121\16\5\15\0\3\5\1\122\21\5\15\0"+
    "\3\5\1\123\21\5\15\0\13\5\1\124\11\5\15\0"+
    "\10\5\1\125\14\5\15\0\25\5\1\0\1\126\13\0"+
    "\16\5\1\127\6\5\15\0\12\5\1\130\12\5\15\0"+
    "\4\5\1\131\20\5\15\0\4\5\1\132\20\5\15\0"+
    "\11\5\1\133\13\5\15\0\11\5\1\134\13\5\15\0"+
    "\11\5\1\135\13\5\16\0\1\136\40\0\4\5\1\137"+
    "\20\5\15\0\25\5\1\0\1\140\13\0\14\5\1\141"+
    "\10\5\20\0\1\142\36\0\3\5\1\143\21\5\22\0"+
    "\1\144\34\0\4\5\1\145\20\5\14\0\30\146\1\0"+
    "\11\146\12\0\1\147\50\0\1\150\20\0\30\151\1\0"+
    "\11\151";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2652];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\16\1\1\11\1\1\6\11\26\1\1\0"+
    "\21\1\1\0\16\1\1\11\5\1\1\0\7\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public Scanner(java.io.InputStream r, ComplexSymbolFactory sf){
		this(r);
		this.sf=sf;
	}
	public Symbol symbol(String plaintext,int code){
	    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar));
	}
	public Symbol symbol(String plaintext,int code,Integer number){
	    return sf.newSymbol(plaintext,code,new Location("",yyline+1, yycolumn +1,yychar), new Location("",yyline+1,yycolumn+yylength(),yychar),number);
	}
	private ComplexSymbolFactory sf;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 94) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 16: 
          { System.out.println("AND");
          }
        case 34: break;
        case 6: 
          { return symbol("Semicolon",sym.SEMI);
          }
        case 35: break;
        case 2: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 36: break;
        case 23: 
          { System.out.println("COMMENT IN SOMES LINE");
          }
        case 37: break;
        case 8: 
          { return symbol("Minus",sym.MINUS);
          }
        case 38: break;
        case 28: 
          { System.out.println("RETURN");
          }
        case 39: break;
        case 30: 
          { System.out.println("INTEGER");
          }
        case 40: break;
        case 21: 
          { System.out.println("NULL");
          }
        case 41: break;
        case 9: 
          { return symbol("Left Bracket",sym.LPAREN);
          }
        case 42: break;
        case 18: 
          { System.out.println("FOR");
          }
        case 43: break;
        case 7: 
          { return symbol("Plus",sym.PLUS);
          }
        case 44: break;
        case 24: 
          { System.out.println("break");
          }
        case 45: break;
        case 10: 
          { return symbol("Right Bracket",sym.RPAREN);
          }
        case 46: break;
        case 27: 
          { System.out.println("WHILE");
          }
        case 47: break;
        case 15: 
          { System.out.println("COMMENT IN ONE LINE");
          }
        case 48: break;
        case 29: 
          { System.out.println("EXTERN");
          }
        case 49: break;
        case 22: 
          { System.out.println("VOID");
          }
        case 50: break;
        case 20: 
          { System.out.println("else");
          }
        case 51: break;
        case 32: 
          { System.out.println("true");
          }
        case 52: break;
        case 25: 
          { System.out.println("class");
          }
        case 53: break;
        case 33: 
          { System.out.println("false");
          }
        case 54: break;
        case 14: 
          { System.out.println("Class");
          }
        case 55: break;
        case 17: 
          { System.out.println("NOT");
          }
        case 56: break;
        case 3: 
          { System.out.println("CONST");
          }
        case 57: break;
        case 1: 
          { System.out.println("IDENTIFIER");
          }
        case 58: break;
        case 19: 
          { System.out.println("bool");
          }
        case 59: break;
        case 11: 
          { return symbol("Integral Number",sym.NUMBER, new Integer(yytext()));
          }
        case 60: break;
        case 31: 
          { System.out.println("continue");
          }
        case 61: break;
        case 5: 
          { return symbol("Times",sym.TIMES);
          }
        case 62: break;
        case 26: 
          { System.out.println("float");
          }
        case 63: break;
        case 12: 
          { System.out.println("OR");
          }
        case 64: break;
        case 13: 
          { System.out.println("if");
          }
        case 65: break;
        case 4: 
          { /* ignore white space. */
          }
        case 66: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return sf.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
