
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Wed Aug 31 23:43:18 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ADDASSIGNMENT = 38;
  public static final int NUMBER_I = 42;
  public static final int LKEY = 21;
  public static final int LBRACKET = 19;
  public static final int NUMBER_F = 43;
  public static final int DIVIDED = 27;
  public static final int INTEGER = 3;
  public static final int LPAREN = 17;
  public static final int GREATER = 33;
  public static final int SEMI = 15;
  public static final int CONTINUE = 6;
  public static final int LESS = 31;
  public static final int FOR = 9;
  public static final int MINUS = 29;
  public static final int RPAREN = 18;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int EQUALTO = 35;
  public static final int OR = 24;
  public static final int BOOL = 2;
  public static final int COMMA = 16;
  public static final int CLASS = 12;
  public static final int EXTERN = 14;
  public static final int PLUS = 28;
  public static final int IF = 7;
  public static final int ID = 41;
  public static final int GREATEROREQ = 34;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 37;
  public static final int RBRACKET = 20;
  public static final int RKEY = 22;
  public static final int error = 1;
  public static final int BREAK = 5;
  public static final int VOID = 11;
  public static final int TIMES = 30;
  public static final int BOOLEAN_VALUE = 44;
  public static final int ELSE = 8;
  public static final int POINT = 40;
  public static final int WHILE = 10;
  public static final int NOTEQUALTO = 36;
  public static final int FLOAT = 4;
  public static final int LESSOREQ = 32;
  public static final int PERCENTAGE = 26;
  public static final int SUBASSIGNMENT = 39;
}

