
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Wed Aug 31 15:53:59 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ADDASSIGNMENT = 39;
  public static final int NUMBER_I = 44;
  public static final int LKEY = 22;
  public static final int LBRACKET = 20;
  public static final int NUMBER_F = 45;
  public static final int DIVIDED = 28;
  public static final int INTEGER = 3;
  public static final int LPAREN = 18;
  public static final int GREATER = 34;
  public static final int SEMI = 16;
  public static final int CONTINUE = 6;
  public static final int LESS = 32;
  public static final int FOR = 9;
  public static final int MINUS = 30;
  public static final int RPAREN = 19;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int EQUALTO = 36;
  public static final int OR = 25;
  public static final int BOOL = 2;
  public static final int COMMA = 17;
  public static final int CLASS = 13;
  public static final int EXTERN = 15;
  public static final int PLUS = 29;
  public static final int IF = 7;
  public static final int ID = 43;
  public static final int GREATEROREQ = 35;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 38;
  public static final int RBRACKET = 21;
  public static final int RKEY = 23;
  public static final int error = 1;
  public static final int NULL = 12;
  public static final int NUMBER = 42;
  public static final int BREAK = 5;
  public static final int VOID = 11;
  public static final int TIMES = 31;
  public static final int BOOLEAN_VALUE = 46;
  public static final int ELSE = 8;
  public static final int POINT = 41;
  public static final int WHILE = 10;
  public static final int NOTEQUALTO = 37;
  public static final int FLOAT = 4;
  public static final int LESSOREQ = 33;
  public static final int PERCENTAGE = 27;
  public static final int SUBASSIGNMENT = 40;
}

