
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Tue Aug 30 13:03:11 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int EXTERN = 14;
  public static final int AND = 22;
  public static final int CONTINUE = 4;
  public static final int CLASS = 3;
  public static final int ELSE = 5;
  public static final int PLUS = 16;
  public static final int OR = 23;
  public static final int RPAREN = 20;
  public static final int SEMI = 15;
  public static final int WHILE = 13;
  public static final int NOT = 24;
  public static final int RETURN = 11;
  public static final int TRUE = 21;
  public static final int IF = 9;
  public static final int LPAREN = 19;
  public static final int FLOAT = 7;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int BREAK = 2;
  public static final int MINUS = 17;
  public static final int FALSE = 6;
  public static final int error = 1;
  public static final int BOOL = 27;
  public static final int INTEGER = 10;
  public static final int FOR = 8;
  public static final int NULL = 25;
  public static final int VOID = 12;
}

